language: php

sudo: false

php:
  - 5.6

env:
  global:
    - DB_USER=root
    - DB_HOST=localhost
    - DB_NAME=test_prestashop

before_script:
  - bash tests/bin/clone_prestashop.sh
  - cp ../PrestaShop/tests/parameters.yml.travis ../PrestaShop/app/config/parameters.yml
  - bash ../PrestaShop/travis-scripts/install-prestashop

script:
  - bash tests/bin/script.sh
  - php ../PrestaShop/vendor/bin/phpunit -c phpunit.xml.dist

deploy:
  skip_cleanup: true
  provider: script
  script: make
  on:
    php: 5.6
    branch: master
    condition: "$DEPLOY = true"
