os: linux
dist: trusty

language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

before_script: make before_script

script: make test

stages:
  - test

jobs:
  include:
    - php: 5.6
      env: BRANCH=1.6.1.18 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.18 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.18 COMPOSER_IN_TESTS=1

    - php: 5.6
      env: BRANCH=1.6.1.19 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.19 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.19 COMPOSER_IN_TESTS=1

    - php: 5.6
      env: BRANCH=1.6.1.20 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.20 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.20 COMPOSER_IN_TESTS=1

    - php: 5.6
      env: BRANCH=1.6.1.21 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.21 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.21 COMPOSER_IN_TESTS=1

    - php: 5.6
      env: BRANCH=1.6.1.22 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.22 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.22 COMPOSER_IN_TESTS=1

    - php: 5.6
      env: BRANCH=1.6.1.23 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.23 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.23 COMPOSER_IN_TESTS=1

    - php: 5.6
      env: BRANCH=1.6.1.24 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.24 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.24 COMPOSER_IN_TESTS=1

    - php: 7.1
      env: BRANCH=1.7.5.x
    - php: 7.2
      env: BRANCH=1.7.5.x
      after_success: bash <(curl -s https://codecov.io/bash)

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: make
#  on:
#    php: 7.2
#    branch: master
#    condition: "$DEPLOY = true"
