language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

sudo: required
dist: trusty

php:
  - 7.1
  - 7.2

matrix:
  include:
  - php: 5.6
    env: BRANCH=1.6.1.1 COMPOSER_IN_TESTS=1
  - php: 7.0
    env: BRANCH=1.6.1.1 COMPOSER_IN_TESTS=1
  - php: 7.1
    env: BRANCH=1.6.1.1 COMPOSER_IN_TESTS=1

before_script: make before_script

script: make test

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: make
#  on:
#    php: 7.2
#    branch: master
#    condition: "$DEPLOY = true"
