os: linux

language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

dist: trusty

jobs:
  include:
    - php: 5.6
      env: BRANCH=1.6.1.24 COMPOSER_IN_TESTS=1
    - php: 7.0
      env: BRANCH=1.6.1.24 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.6.1.24 COMPOSER_IN_TESTS=1
    - php: 7.1
      env: BRANCH=1.7.5.x
    - php: 7.2
      env: BRANCH=1.7.5.x

before_script: make before_script

script: make test

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: make
#  on:
#    php: 7.2
#    branch: master
#    condition: "$DEPLOY = true"
