version: '3'
services:
  app:
    build:
      context: ./.docker
    volumes:
      - ./:/code
    links:
      - "mysql"
    depends_on:
      - mysql
    environment:
      - DB_NAME=presta
      - DB_USER=presta
      - DB_PASS=presta
      - DB_HOST=presta
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=presta
      - MYSQL_USER=presta
      - MYSQL_PASSWORD=presta
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"